version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      minor-and-patch:
        exclude-patterns:
          - "testcontainers"
        update-types:
          - "minor"
          - "patch"
      testcontainers:
        patterns:
          - "testcontainers"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "maven"
    directory: "/analysis-service"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      maven-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "docker"
    directory: "/analysis-service"
    schedule:
      interval: "weekly"
      day: "sunday"
