-- ─────────────────────────────────────────────────────────────────────────────
-- V1 – Initiales Schema des Unfallatlas Analysis Service.
--
-- Spiegelt die JPA-Entitäten aus `de.unfallatlas.analysis.domain` 1:1 wider:
--
--   - location_action_brief                (Aggregat-Wurzel)
--       embedded:  versioning              (rules_version, scoring_version,
--                                           profile_version, generated_at)
--       embedded:  ai_assessment_metadata  (ai_model, ai_prompt_version,
--                                           ai_input_fingerprint, ai_source)
--   - conflict_pattern_assessment          (1:n)
--   - candidate_measure_assessment         (1:n)
--   - prioritization_profile_score         (1:n, eindeutig pro brief+profile)
--   - political_reference_summary          (1:n)
--   - analysis_job                         (Job-/Queue-Vorbereitung,
--                                           noch keine Vollorchestrierung)
--
-- Das Skript ist bewusst portabel zwischen PostgreSQL (Prod) und H2 im
-- PostgreSQL-Kompatibilitätsmodus (Tests/Dev) gehalten:
--   - keine PostgreSQL-spezifischen Typen wie JSONB, GEOMETRY, …
--   - Identity-Spalten via `BIGINT GENERATED BY DEFAULT AS IDENTITY`
--   - keine Trigger, keine Funktionen
--
-- PostGIS-/Geometriespalten werden bewusst (noch) nicht angelegt; geometrische
-- Auswertungen leben weiterhin in der Node-App.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE location_action_brief (
    id                      VARCHAR(36)   NOT NULL,
    location_key            VARCHAR(200)  NOT NULL,
    external_location_id    VARCHAR(200),
    city                    VARCHAR(100)  NOT NULL,
    title                   VARCHAR(250)  NOT NULL,
    created_at              TIMESTAMP     NOT NULL,
    updated_at              TIMESTAMP     NOT NULL,
    schema_version          VARCHAR(60)   NOT NULL,
    source_fingerprint      VARCHAR(128)  NOT NULL,
    profile_key             VARCHAR(60)   NOT NULL,
    deterministic_summary   VARCHAR(4000),
    confidence              DOUBLE PRECISION NOT NULL,
    data_quality            VARCHAR(10)   NOT NULL,
    political_readiness     VARCHAR(10)   NOT NULL,
    ai_used                 BOOLEAN       NOT NULL,
    -- embedded VersioningInfo
    rules_version           VARCHAR(60)   NOT NULL,
    scoring_version         VARCHAR(60)   NOT NULL,
    profile_version         VARCHAR(60)   NOT NULL,
    generated_at            TIMESTAMP     NOT NULL,
    -- embedded AiAssessmentMetadata (alle nullable)
    ai_model                VARCHAR(80),
    ai_prompt_version       VARCHAR(80),
    ai_input_fingerprint    VARCHAR(128),
    ai_source               VARCHAR(30),
    CONSTRAINT pk_location_action_brief PRIMARY KEY (id)
);

CREATE INDEX idx_lab_location_key ON location_action_brief (location_key);
CREATE INDEX idx_lab_city         ON location_action_brief (city);
CREATE INDEX idx_lab_profile_key  ON location_action_brief (profile_key);
CREATE INDEX idx_lab_created_at   ON location_action_brief (created_at);

-- ─── Sub-Entitäten ─────────────────────────────────────────────────────────

CREATE TABLE conflict_pattern_assessment (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brief_id                        VARCHAR(36)  NOT NULL,
    pattern_id                      VARCHAR(80)  NOT NULL,
    alias_id                        VARCHAR(80),
    label                           VARCHAR(200) NOT NULL,
    classification                  VARCHAR(12)  NOT NULL,
    confidence                      VARCHAR(10)  NOT NULL,
    rationale                       VARCHAR(1000),
    evidence_joined                 VARCHAR(2000),
    requires_on_site_check_joined   VARCHAR(2000),
    CONSTRAINT pk_conflict_pattern_assessment PRIMARY KEY (id),
    CONSTRAINT fk_cpa_brief FOREIGN KEY (brief_id)
        REFERENCES location_action_brief (id) ON DELETE CASCADE
);

CREATE INDEX idx_cpa_pattern_id ON conflict_pattern_assessment (pattern_id);
CREATE INDEX idx_cpa_alias_id   ON conflict_pattern_assessment (alias_id);

CREATE TABLE candidate_measure_assessment (
    id                                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brief_id                                 VARCHAR(36)  NOT NULL,
    measure_id                               VARCHAR(80)  NOT NULL,
    title                                    VARCHAR(200) NOT NULL,
    category                                 VARCHAR(60),
    source_category                          VARCHAR(60),
    fit_score                                DOUBLE PRECISION NOT NULL,
    quick_win_potential                      DOUBLE PRECISION NOT NULL,
    implementation_effort                    VARCHAR(12),
    cost_band                                VARCHAR(12),
    why_preselected                          VARCHAR(1000),
    matched_conflict_patterns_joined         VARCHAR(2000),
    matched_risk_factors_joined              VARCHAR(2000),
    expected_target_accident_types_joined    VARCHAR(2000),
    position                                 INTEGER      NOT NULL,
    CONSTRAINT pk_candidate_measure_assessment PRIMARY KEY (id),
    CONSTRAINT fk_cma_brief FOREIGN KEY (brief_id)
        REFERENCES location_action_brief (id) ON DELETE CASCADE
);

CREATE INDEX idx_cma_measure_id ON candidate_measure_assessment (measure_id);
CREATE INDEX idx_cma_fit_score  ON candidate_measure_assessment (fit_score);

CREATE TABLE prioritization_profile_score (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brief_id                            VARCHAR(36) NOT NULL,
    profile_key                         VARCHAR(60) NOT NULL,
    total                               DOUBLE PRECISION NOT NULL,
    safety_impact_score                 DOUBLE PRECISION NOT NULL,
    severe_accident_reduction_score     DOUBLE PRECISION NOT NULL,
    bicycle_safety_score                DOUBLE PRECISION NOT NULL,
    quick_win_score                     DOUBLE PRECISION NOT NULL,
    implementation_feasibility_score    DOUBLE PRECISION NOT NULL,
    policy_readiness_score              DOUBLE PRECISION NOT NULL,
    cost_efficiency_score               DOUBLE PRECISION NOT NULL,
    data_confidence_score               DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_prioritization_profile_score PRIMARY KEY (id),
    CONSTRAINT fk_pps_brief FOREIGN KEY (brief_id)
        REFERENCES location_action_brief (id) ON DELETE CASCADE,
    CONSTRAINT uq_pps_brief_profile UNIQUE (brief_id, profile_key)
);

CREATE INDEX idx_pps_profile_key ON prioritization_profile_score (profile_key);
CREATE INDEX idx_pps_total       ON prioritization_profile_score (total);

CREATE TABLE political_reference_summary (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    brief_id    VARCHAR(36)  NOT NULL,
    title       VARCHAR(250) NOT NULL,
    url         VARCHAR(500),
    type        VARCHAR(60),
    topic       VARCHAR(60),
    relevance   DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_political_reference_summary PRIMARY KEY (id),
    CONSTRAINT fk_prs_brief FOREIGN KEY (brief_id)
        REFERENCES location_action_brief (id) ON DELETE CASCADE
);

CREATE INDEX idx_prs_topic ON political_reference_summary (topic);

-- ─── Job-/Queue-Vorbereitung (noch keine Orchestrierung) ───────────────────
--
-- Persistierbares Job-Modell für spätere Batch-/Queue-Funktionen (z. B.
-- "stadtweite Neuberechnung", "städtische Top-Liste neu indexieren",
-- "Hibernate-Search-Reindex").  In diesem PR existiert nur die Tabelle und
-- ein einfaches Repository – die Verarbeitung selbst kommt im Folge-PR.

CREATE TABLE analysis_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_type            VARCHAR(60)  NOT NULL,
    status              VARCHAR(12)  NOT NULL,
    target_city         VARCHAR(100),
    target_profile_key  VARCHAR(60),
    payload             VARCHAR(4000),
    last_error          VARCHAR(2000),
    attempts            INTEGER      NOT NULL,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    CONSTRAINT pk_analysis_job PRIMARY KEY (id)
);

CREATE INDEX idx_aj_status     ON analysis_job (status);
CREATE INDEX idx_aj_job_type   ON analysis_job (job_type);
CREATE INDEX idx_aj_created_at ON analysis_job (created_at);
